name: ASCII Dragon Generation
on: push

jobs:
    ascii-dragon:
        name: ascii-dragon-job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: execute Shell Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh