name: first action
on: push
jobs:
    first-job:
        name: read files
        runs-on: ubuntu-latest
        steps:
            - name: display text
              run: echo "Hey! My first task in Github Actions"
            - name: list the directory
              run: ls -la
            - name: read the files
              run: cat README.md

