name: Variables and Secrets
on: push

env:
    DOCKER_USERNAME: praravind1801
jobs:
    build-job:
        name: docker build
        runs-on: ubuntu-latest
        env:
            DOCKER_IMAGE: github-actions-build
        steps:
            - name: docker build
              run: echo docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
              env:
                DOCKER_TAG: latest
            - name: docker login
              run: echo docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: docker push
              run: echo docker push ${{ env.DOCKER_USERNAME }}${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
              env:
                DOCKER_TAG: latest
    deploy-job:
        name: docker images
        runs-on: ubuntu-latest
        env:
            DOCKER_IMAGE: github-actions-deploy
        steps:
            - name: check docker image
              run: echo docker image ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
              env:
                DOCKER_TAG: latest
            - name: status of workflow
              run: echo The workflow is ${{ vars.status }}